[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
presale = "HYp1PfQuDH8N24J5pe2TjekahawdwFzM5F2GUyqhZQhY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
